services:
  reg-pilot-api:
    image: gleif/reg-pilot-api:0.1.0
    platform: linux/amd64
    network_mode: host
    ports:
      - 8000:8000
    environment:
      - ENABLE_CORS=true
      - VLEI_VERIFIER=http://localhost:7676
      - FILER_REPORTS=http://localhost:7676/reports/
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    extra_hosts:
      - 'localhost:127.0.0.1'

  verify:
    image: alpine
    command: ["echo", "Dependencies running"]
    depends_on:
      reg-pilot-api:
        condition: service_healthy
